### ISSUE TITLE
Text blocks are completely lost 

### ISSUE THREAD

**Issue by jocowhite** [art-r/tex-to-txt#2]
In the following 2 examples texts are not transferred to the txt file:

1. Example:
\subsection{Methode III - Dimensionsreduktion}\label{section:methode_3}

% Über PCA schreiben
Die Principal Component Analysis \ac{PCA} ist eine der bekanntesten Techniken für die Dimensionsreduktion.\footnote{Vgl. \cite[S. 4.]{S15_10060625}}
Durch eine \ac{PCA} können die wichtigsten Merkmale in wenige Komponenten/Dimensionen dargestellt werden. 
Bei einer \ac{PCA} wird das mathematische Modell der Singulärwertzerlegung genutzt, um die Hauptkomponenten der Daten zu ermitteln. 
Die Singulärwertzerlegung teilt die Matrix der Daten $X$ in die drei Komponenten $U$ welche die Eigenwerte beinhaltet, $\Sigma$ beinhaltet die Varianz der einzelnen Dimensionen und $V^T$.
Die \ac{PCA} nutzt folgenden Ablauf, um die Dimensionen eines Datensatzes zu reduzieren.

\begin{enumerate}
    \item Zentrierung des Datensatzes $X$ durch eine subtraktion des Mittelwerts $m$ 
    \begin{equation}\label{eq:SDV}  \tilde{x_i} = x_i - m \end{equation}
    \item Berechnung der Singulärwertzerlegung
    \begin{equation}\label{eq:SDV}  X = U \Sigma V^T \end{equation}
    \item Datensatz auf die Hauptkomponente projizieren
\end{enumerate}

   

\begin{equation}\label{eq:SDV}
    X = U \sum V^T
\end{equation}

2. Example: 
\subsection{Methode I - Synthetische Daten}\label{section:methode_1}

Durch den selection Bias, kommt es in Daten häufig dazu, dass bestimmte Gruppen unterrepräsentiert sind. 
Dadurch werden häufig diversere Daten benötigt, um Fairness sicherzustellen.\footnote{Vgl. \cite[S. 1]{50_genEthos}}
%Quelle 50->7 mal checken 
Es gibt unterschiedliche Konzepte, um mittels mathematischer Modelle künstlich generierte Daten zu erhalten, 
 welche die ungleiche Datenverteilung reduzieren soll. 
Die Wissenschaft entwickelt dabei unterschiedliche Verfahren, mit welchen künstliche Daten generiert werden können.\footnote{Vgl. \cite[S. 1826]{S3_LearningImbalanced}}
So werden unter anderem regressions Algorithmen, Hidden Markov Models und Deep Learning Verfahren verwendet.\footnote{Vgl. \cite[S. 1]{54_SynGen}}

%schreiben über Copula
Einige Konzepte zur Datenaufbereitung basieren auf dem Copula Konzept, welches auf der Wahrscheinlichkeitstheorie und Statistik basiert.
Innerhalb des Konzepts liegt die marginale Wahrscheinlichkeitsverteilung jeder Variable gleichmäßig im Intervall zwischen null und eins.\footnote{Vgl. \cite[S. 2]{54_SynGen}}
Um eine Abhängigkeit zwischen den einzelnen Zufallsvariablen zu beschreiben, werden Copulas verwendet.
Eine Coupla beschreibt dabei eine multivariate Verteilungsfunktion. 
%CTGAN Modell
Eine weitere Art von \ac{NN} welches für die Generierung von künstlichen Daten verwendet wird, ist das \ac{GAN}. 
Diese Art von Netzwerk besteht aus einem Generator-Modell und einem Diskriminator-Modell.\footnote{Vgl. \cite[S. 161005.]{S12_sabuhi2021applications}} 
Während das Generator-Modell versucht künstliche Daten zu generieren, versucht das Diskriminator-Modell die generierten Daten von echten Daten zu unterscheiden 
 und somit schlechte Resultate des Generator-Modells zu bestrafen.\footnote{Vgl. \cite[S. 642]{57_Study_GAN}}
Ein \ac{GAN} Modell, welches explizit für tabellarische Werte entwickelt wurde ist das CT\ac{GAN},
 dieses nutzt einen konditionellen Generator, um explizit tabellarische Werte zu generieren.\footnote{Vgl. \cite[S. 1]{52_Conditional_GAN}}
Das CT\ac{GAN} Modell beinhaltet die Hauptaspekte eines conditional vectors, eines generator loss und einer training by sampling Methode. 
Der genaue Aufbau wird in Abbildung \ref{abb:CTGAN} dargestellt.

\begin{figure}[htb]
    % Zentrierung
    \centering
    % Einfügen der Datei, mit angepasster Höhe
    \includegraphics[height=5cm]{lib/img/CTGAN.png}
    % Titel und Label der Grafik
    \caption[Aufbau eines CTGAN Netzwerks]{Aufbau eines CTGAN Netzwerks\footnote{\cite[Enthalten in:]{52_Conditional_GAN}}}
    \label{abb:CTGAN}
\end{figure}

**Comment by only-a-user** [comment]
This is fixed with pull request #5.
